apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-database.c706ecugaxha.ap-south-1.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-database.c706ecugaxha.ap-south-1.rds.amazonaws.com:3306/foodcatalogdb
  userdb_url: jdbc:mysql://mysql-database.c706ecugaxha.ap-south-1.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:VishalSingh@cluster0.pswqba8.mongodb.net/
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  